---
collections:
  - name: ansible.netcommon
  - name: f5networks.f5_modules
    source: https://github.com/F5Networks/f5-ansible-f5modules#ansible_collections/f5networks/f5_modules
    type: git
    version: 1.31.0
  - name: f5networks.f5_bigip
    source: https://github.com/F5Networks/f5-ansible-bigip.git#ansible_collections/f5networks/f5_bigip
    type: git
    version: devel
