- name: Upload ASM template
  hosts: localhost
  gather_facts: false
  vars:
    src_url: "https://raw.githubusercontent.com/Nikoolayy1/awx-example-playbooks/refs/heads/main/ansible-asm.xml"
    filename: "{{ src_url | basename }}"
    local_file: "/tmp/ansible-asm.xml"
  tasks:
    - name: Download file from GitHub
      ansible.builtin.get_url:
        url: "{{ src_url }}"
        dest: "{{ local_file }}"
        mode: "0644"
    - name: Get file size
      ansible.builtin.stat:
        path: "{{ local_file }}"
      register: file_stat
    - name: Upload file to F5
      ansible.builtin.uri:
        url: "https://{{ server }}/mgmt/tm/asm/file-transfer/uploads/{{ filename }}"
        method: POST
        user: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        force_basic_auth: true
        validate_certs: false
        headers:
          Content-Type: "application/octet-stream"
          Content-Range: "0-{{ file_stat.stat.size | int - 2 }}/{{ file_stat.stat.size | int - 1 }}"
        body: "{{ lookup('file', local_file) }}"
        status_code: 200
      register: file_result
    - name: Print BIG-IP file upload status
      debug:
        msg: "{{ file_result.json }}"
    - name: Import ASM (raw inline JSON)
      ansible.builtin.uri:
        url: "https://{{ server }}/mgmt/tm/asm/tasks/import-policy-template"
        method: POST
        user: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        force_basic_auth: yes
        validate_certs: no
        headers:
          Content-Type: "application/json" 
        body_format: json
        body:
          name: ansible-2
          filename: " {{ filename }} "
        status_code: 201
      register: template_result
    - name: Print BIG-IP template status
      debug:
        msg: "{{ template_result.json }}"
