- name: Palo Alto dynamic command
  hosts: all
  connection: local
  gather_facts: false
  vars:
    device:
      ip_address: "{{ ansible_host }}"
      username: "{{ palo_user }}"
      password: "{{ palo_pass }}"
  tasks:
    - name: Run dynamic command
      paloaltonetworks.panos.panos_op:
        provider: "{{ device }}"
        cmd: "{{ pa_cmd }}"
      register: result
    - debug:
        msg: "{{ result.stdout }}"
