- name: GRAB F5 FACTS
  hosts: all
  connection: local
  gather_facts: no
  vars:
#   service_name: httpd
  tasks:
  - name: Manage BIG-IP service lifecycle
    block:
    - name: Set provider with BIG-IP login information
      set_fact:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          server_port: 443
          validate_certs: no
    - name: Show BIG-IP status before
      f5networks.f5_modules.bigip_command:
        commands: "show cm failover-status"
        provider: "{{ provider }}"
      register: cm_result
    - name: Print BIG-IP status before
      debug:
        msg: "{{ cm.stdout }}"
    - name: Show service status before
      f5networks.f5_modules.bigip_command:
        commands: "show sys service {{ service_name }}"
        provider: "{{ provider }}"
      register: status_result
    - name: Print service status before
      debug:
        msg: "{{ status_result.stdout }}"
    - name: Restart service
      f5networks.f5_bigip.bigip_command:
        commands: "restart sys service {{ service_name }}"
        provider: "{{ provider }}"
      register: bigrestart_result
    - name: Show restart output
      debug:
        msg: "{{ bigrestart_result.stdout }}"
    - name: Show service status after
      f5networks.f5_bigip.bigip_command:
        commands: "show sys service {{ service_name }}"
        provider: "{{ provider }}"
      register: statusnew_result
    - name: Print service status after
      debug:
        msg: "{{ statusnew_result.stdout }}"
#    when: "'f5-devices' not in group_names"

