- name: Check and restart service using bigstart
  hosts: all
  gather_facts: false
  vars:
#   service_name: httpd     # â† change as needed
  tasks:
    - block:
        - name: Get failover state
          ansible.builtin.shell: tmsh show sys failover | awk '{print $2}'
          register: failover_state
        - name: Show failover state
          debug:
            msg: "{{ failover_state.stdout }}"
        - name: Run bigstart status {{ service_name }}
          ansible.builtin.shell: "bigstart status {{ service_name }}"
          register: bigstart_result
        - name: Show initial status
          debug:
            msg: "{{ bigstart_result.stdout }}"
        - name: Restart {{ service_name }}
          ansible.builtin.shell: "bigstart restart {{ service_name }}"
          register: bigrestart_result
        - name: Show restart output
          debug:
            msg: "{{ bigrestart_result.stdout }}"
        - name: Run new bigstart status {{ service_name }}
          ansible.builtin.shell: "bigstart status {{ service_name }}"
          register: bigstartnew_result
        - name: Show new status
          debug:
            msg: "{{ bigstartnew_result.stdout }}"
        - name: Get failover state again
          ansible.builtin.shell: tmsh show sys failover | awk '{print $2}'
          register: failover_state_new
        - name: Show failover state
          debug:
            msg: "{{ failover_state_new.stdout }}"
#    when: "'f5-devices' not in group_names"
