- name: GRAB F5 FACTS
  hosts: lb
  connection: local
  gather_facts: no
  tasks:
  - name: Set a fact named 'provider' with BIG-IP login information
    set_fact:
     provider:
      server: "{{ ansible_host }}"
      user: "{{ansible_user}}"
      password: "{{ansible_password}}"
      server_port: 8443
      validate_certs: no 
- name: run show version on remote devices
  bigip_command:
    commands: show sys version
    provider: "{{provider}}"
  delegate_to: localhost
