- name: RESTART F5 service
  hosts: all
  gather_facts: no
  vars:
  tasks:
  - name: Manage BIG-IP service lifecycle
    block:
    - name: Set provider with BIG-IP login information
      set_fact:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          server_port: 443
          validate_certs: no
    - name: Set the failover.nettimeoutsec DB variable on the BIG-IP to 10 seconds
      bigip_sys_db:
        key: failover.nettimeoutsec
        value: 10
        provider: "{{ provider }}"
      delegate_to: localhost
    - name: Show BIG-IP status before
      f5networks.f5_modules.bigip_command:
        commands: "show cm failover-status"
        provider: "{{ provider }}"
      register: cm_result
      delegate_to: localhost
    - name: Print BIG-IP status before
      debug:
        msg: "{{ cm_result.stdout[0] }}"
    - name: Show service status before
      f5networks.f5_modules.bigip_command:
        commands: "show sys service {{ service_name }}"
        provider: "{{ provider }}"
      register: status_result
      delegate_to: localhost
    - name: Print service status before
      debug:
        msg: "{{ status_result.stdout }}"
    - name: Restart service
      f5networks.f5_modules.bigip_command:
        commands: "restart sys service {{ service_name }}"
        provider: "{{ provider }}"
      register: bigrestart_result
      delegate_to: localhost
    - name: Show restart output
      debug:
        msg: "{{ bigrestart_result.stdout }}"
    - name: Show service status after
      f5networks.f5_modules.bigip_command:
        commands: "show sys service {{ service_name }}"
        provider: "{{ provider }}"
      register: statusnew_result
      delegate_to: localhost
    - name: Print service status after
      debug:
        msg: "{{ statusnew_result.stdout }}"
    - name: 10 second pause
      ansible.builtin.pause:
        seconds: 10
    - name: Show BIG-IP status after
      f5networks.f5_modules.bigip_command:
        commands: "show cm failover-status"
        provider: "{{ provider }}"
      register: cm_new_result
      delegate_to: localhost
    - name: Print BIG-IP status after
      debug:
        msg: "{{ cm_new_result.stdout[0] }}"
    - name: Set the failover.nettimeoutsec DB variable on the BIG-IP to 5 seconds
      bigip_sys_db:
        key: failover.nettimeoutsec
        value: 5
        provider: "{{ provider }}"
      ignore_errors: yes

#    when: "'f5-devices' not in group_names"

