- name: Palo Alto SSH
  hosts: all
  gather_facts: false
  tasks:
    - name: Show system info
      ansible.netcommon.cli_command:
        command: show system info
      register: out
    - debug:
        msg: "{{ out.stdout }}"
