---
- name: Palo Alto SSH
  hosts: all
  gather_facts: false
  collections:
    - ansible.netcommon
  tasks:
    - name: Show system info
      ansible.netcommon.cli_command:
        command: show system info
      register: out
    - debug:
        var: out.stdout
