- name: GRAB F5 FACTS
  hosts: all
  connection: local
  gather_facts: no
  vars:
#   service_name: httpd     # ← change as needed
  tasks:
  - name: Set a fact named 'provider' with BIG-IP login information
    set_fact:
      provider:
        server: "{{ ansible_host }}"
        user: "{{ansible_user}}"
        password: "{{ansible_password}}"
        server_port: 443
        validate_certs: no 
  - name: run restart service
    bigip_command:
      commands: "restart sys service {{ service_name }}"
      provider: "{{provider}}"
    delegate_to: localhost
    register: bigrestart_result
  - name: Show restart output
    debug:
      msg: "{{ bigrestart_result.stdout }}"
      
